# Generated by Django 3.1.7 on 2021-06-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=225)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('subject', models.CharField(max_length=225)),
                ('message', models.CharField(max_length=225)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
