# Generated by Django 3.1.5 on 2021-01-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='role_name',
            new_name='role',
        ),
    ]
