# Generated by Django 3.1.7 on 2021-03-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_auto_20210308_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactTeam',
        ),
    ]
